// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVHSMk4YuVjhhaUIOvWykqZ_DMAZHlI7k',
    appId: '1:287910848295:web:14ac76cc5232a46f302b02',
    messagingSenderId: '287910848295',
    projectId: 'signupapp-e1252',
    authDomain: 'signupapp-e1252.firebaseapp.com',
    storageBucket: 'signupapp-e1252.firebasestorage.app',
    measurementId: 'G-84Q335J5WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQiN0S01oI7-woLiCACKDuLfzCWYknkFE',
    appId: '1:287910848295:android:42404003c760b42a302b02',
    messagingSenderId: '287910848295',
    projectId: 'signupapp-e1252',
    storageBucket: 'signupapp-e1252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGFew9plNAARpQ1tXnfUEtW8LXhNAljbw',
    appId: '1:287910848295:ios:c1db39a3608c0a93302b02',
    messagingSenderId: '287910848295',
    projectId: 'signupapp-e1252',
    storageBucket: 'signupapp-e1252.firebasestorage.app',
    iosBundleId: 'com.example.googleSignupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGFew9plNAARpQ1tXnfUEtW8LXhNAljbw',
    appId: '1:287910848295:ios:c1db39a3608c0a93302b02',
    messagingSenderId: '287910848295',
    projectId: 'signupapp-e1252',
    storageBucket: 'signupapp-e1252.firebasestorage.app',
    iosBundleId: 'com.example.googleSignupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVHSMk4YuVjhhaUIOvWykqZ_DMAZHlI7k',
    appId: '1:287910848295:web:7586d63a7906269f302b02',
    messagingSenderId: '287910848295',
    projectId: 'signupapp-e1252',
    authDomain: 'signupapp-e1252.firebaseapp.com',
    storageBucket: 'signupapp-e1252.firebasestorage.app',
    measurementId: 'G-MESBQSHT51',
  );
}
