const Map<String, String> itemSections = {
  // ── Sports / gym
  'ankle straps': 'الرياضة والتمارين',
  'athletic shoes': 'الرياضة والتمارين',
  'athletic tape': 'الرياضة والتمارين',
  'ball pump': 'الرياضة والتمارين',
  'barbell clips': 'الرياضة والتمارين',
  'boxing gloves': 'الرياضة والتمارين',
  'cones': 'الرياضة والتمارين',
  'deadlift socks': 'الرياضة والتمارين',
  'dumbbell': 'الرياضة والتمارين',
  'fins': 'الرياضة والتمارين',
  'glute bands': 'الرياضة والتمارين',
  'grip gloves': 'الرياضة والتمارين',
  'grip socks': 'الرياضة والتمارين',
  'gym gloves': 'الرياضة والتمارين',
  'gym membership card': 'الرياضة والتمارين',
  'hand wraps': 'الرياضة والتمارين',
  'headgear': 'الرياضة والتمارين',
  'jump rope': 'الرياضة والتمارين',
  'knee pads': 'الرياضة والتمارين',
  'knee sleeves': 'الرياضة والتمارين',
  'knee straps': 'الرياضة والتمارين',
  'lacrosse ball': 'الرياضة والتمارين',
  'lifting jack': 'الرياضة والتمارين',
  'lifting shoes': 'الرياضة والتمارين',
  'lifting straps': 'الرياضة والتمارين',
  'liquid chalk': 'الرياضة والتمارين',
  'magnetic timer': 'الرياضة والتمارين',
  'measuring tape': 'الرياضة والتمارين',
  'micro plates': 'الرياضة والتمارين',
  'mouth guard': 'الرياضة والتمارين',
  'nose clip': 'الرياضة والتمارين',
  'nose plug': 'الرياضة والتمارين',
  'paddles': 'الرياضة والتمارين',
  'pulling straps': 'الرياضة والتمارين',
  'resistance band': 'الرياضة والتمارين',
  'shin guard sleeves': 'الرياضة والتمارين',
  'shin guards': 'الرياضة والتمارين',
  'snorkel': 'الرياضة والتمارين',
  'soccer ball': 'الرياضة والتمارين',
  'sports bra': 'الرياضة والتمارين',
  'sports watch': 'الرياضة والتمارين',
  'strap': 'الرياضة والتمارين',
  'swimming cap': 'الرياضة والتمارين',
  'swimming goggles': 'الرياضة والتمارين',
  'swimsuit': 'الرياضة والتمارين',
  'tennis ball': 'الرياضة والتمارين',
  'training shorts': 'الرياضة والتمارين',
  'walking shoes': 'الرياضة والتمارين',
  'weight lifting belt': 'الرياضة والتمارين',
  'weight lifting gloves': 'الرياضة والتمارين',
  'workout clothes': 'الرياضة والتمارين',
  'wrist straps': 'الرياضة والتمارين',
  'wrist wraps': 'الرياضة والتمارين',
  'wristbands': 'الرياضة والتمارين',
  'yoga blocks': 'الرياضة والتمارين',
  'yoga mat': 'الرياضة والتمارين',

  // ── Electronics
  'adapter': 'الإلكترونيات والشواحن',
  'camera': 'الإلكترونيات والشواحن',
  'charger': 'الإلكترونيات والشواحن',
  'computer': 'الإلكترونيات والشواحن',
  'earbuds': 'الإلكترونيات والشواحن',
  'headphones': 'الإلكترونيات والشواحن',
  'ipad': 'الإلكترونيات والشواحن',
  'laptop': 'الإلكترونيات والشواحن',
  'microphone': 'الإلكترونيات والشواحن',
  'phone': 'الإلكترونيات والشواحن',
  'power bank': 'الإلكترونيات والشواحن',
  'ssd': 'الإلكترونيات والشواحن',
  'tablet': 'الإلكترونيات والشواحن',
  'usb adapter': 'الإلكترونيات والشواحن',
  'usb flash drive': 'الإلكترونيات والشواحن',
  'usb hub': 'الإلكترونيات والشواحن',

  // ── Prayer / Haram
  'dua book': 'العبادة والحرم',
  'ihram': 'العبادة والحرم',
  'prayer mat': 'العبادة والحرم',
  'quran': 'العبادة والحرم',
  'tasbeeh': 'العبادة والحرم',

  // ── Study / work
  'book': 'الدراسة والعمل',
  'calculator': 'الدراسة والعمل',
  'chalk': 'الدراسة والعمل',
  'eraser': 'الدراسة والعمل',
  'correction tape': 'الدراسة والعمل',
  'highlighter': 'الدراسة والعمل',
  'id': 'الدراسة والعمل',
  'id card': 'الدراسة والعمل',
  'journal': 'الدراسة والعمل',
  'laser pointer': 'الدراسة والعمل',
  'lecture notes': 'الدراسة والعمل',
  'notebook': 'الدراسة والعمل',
  'paper': 'الدراسة والعمل',
  'paper clip': 'الدراسة والعمل',
  'pen': 'الدراسة والعمل',
  'pencil': 'الدراسة والعمل',
  'pins': 'الدراسة والعمل',
  'planner': 'الدراسة والعمل',
  'presentation clicker': 'الدراسة والعمل',
  'projector remote': 'الدراسة والعمل',
  'protractor': 'الدراسة والعمل',
  'ruler': 'الدراسة والعمل',
  'scissors': 'الدراسة والعمل',
  'sharpener': 'الدراسة والعمل',
  'stapler': 'الدراسة والعمل',
  'sticky notes': 'الدراسة والعمل',
  'student id': 'الدراسة والعمل',
  'study sheets': 'الدراسة والعمل',
  'stylus pen': 'الدراسة والعمل',
  'tape': 'الدراسة والعمل',
  'whiteboard eraser': 'الدراسة والعمل',
  'whiteboard marker': 'الدراسة والعمل',

  // ── Weather
  'cap': 'اقتراحات حسب الطقس',
  'sun hat': 'اقتراحات حسب الطقس',
  'sunglasses': 'اقتراحات حسب الطقس',
  'sunscreen': 'اقتراحات حسب الطقس',
  'umbrella': 'اقتراحات حسب الطقس',
  'uv umbrella': 'اقتراحات حسب الطقس',
  'portable fan': 'اقتراحات حسب الطقس',
  'rain boots': 'اقتراحات حسب الطقس',
  'jacket': 'اقتراحات حسب الطقس',
  'hoodie': 'اقتراحات حسب الطقس',
  'bug spray': 'اقتراحات حسب الطقس',

  // ── Hygiene / personal care
  'body lotion': 'العناية والنظافة',
  'body spray': 'العناية والنظافة',
  'body wash': 'العناية والنظافة',
  'body wipes': 'العناية والنظافة',
  'cleansing balm': 'العناية والنظافة',
  'comb': 'العناية والنظافة',
  'conditioner': 'العناية والنظافة',
  'deodorant': 'العناية والنظافة',
  'disinfectant wipes': 'العناية والنظافة',
  'eye drops': 'العناية والنظافة',
  'face cream': 'العناية والنظافة',
  'face mask': 'العناية والنظافة',
  'face towel': 'العناية والنظافة',
  'face wash': 'العناية والنظافة',
  'facial wipes': 'العناية والنظافة',
  'fragrance free deodorant': 'العناية والنظافة',
  'fragrance free shampoo': 'العناية والنظافة',
  'fragrance free soap': 'العناية والنظافة',
  'hair brush': 'العناية والنظافة',
  'hair clip': 'العناية والنظافة',
  'hair comb': 'العناية والنظافة',
  'hair tie': 'العناية والنظافة',
  'hand cream': 'العناية والنظافة',
  'hand sanitizer': 'العناية والنظافة',
  'lip balm': 'العناية والنظافة',
  'lipstick': 'العناية والنظافة',
  'makeup': 'العناية والنظافة',
  'mirror': 'العناية والنظافة',
  'moisturizer': 'العناية والنظافة',
  'nail clipper': 'العناية والنظافة',
  'pads': 'العناية والنظافة',
  'perfume': 'العناية والنظافة',
  'shampoo': 'العناية والنظافة',
  'shower shoes': 'العناية والنظافة',
  'siwak': 'العناية والنظافة',
  'sponge': 'العناية والنظافة',
  'tissues': 'العناية والنظافة',
  'toothbrush': 'العناية والنظافة',
  'toothpaste': 'العناية والنظافة',
  'towel': 'العناية والنظافة',
  'washbag': 'العناية والنظافة',
  'wet wipes': 'العناية والنظافة',
  'spa headband': 'العناية والنظافة',
  'shoe polish': 'العناية والنظافة',

  // ── Clothes / accessories
  'abaya': 'ملابس وإكسسوارات',
  'accessories': 'ملابس وإكسسوارات',
  'earrings': 'ملابس وإكسسوارات',
  'glasses': 'ملابس وإكسسوارات',
  'glasses case': 'ملابس وإكسسوارات',
  'headband': 'ملابس وإكسسوارات',
  'headscarf': 'ملابس وإكسسوارات',
  'high heels': 'ملابس وإكسسوارات',
  'leggings': 'ملابس وإكسسوارات',
  'pants': 'ملابس وإكسسوارات',
  'sandals': 'ملابس وإكسسوارات',
  'shirt': 'ملابس وإكسسوارات',
  'shoes': 'ملابس وإكسسوارات',
  'shorts': 'ملابس وإكسسوارات',
  'slippers': 'ملابس وإكسسوارات',
  'socks': 'ملابس وإكسسوارات',
  't shirt': 'ملابس وإكسسوارات',
  'tie': 'ملابس وإكسسوارات',
  'underwear': 'ملابس وإكسسوارات',
  'watch': 'ملابس وإكسسوارات',
  'smartwatch': 'ملابس وإكسسوارات',
  'wallet': 'ملابس وإكسسوارات',
  'purse': 'ملابس وإكسسوارات',
  'clothes': 'ملابس وإكسسوارات',
  'sheet set': 'ملابس وإكسسوارات',

  // ── Bags / storage
  'business bag': 'الحقائب والتخزين',
  'crossbody bag': 'الحقائب والتخزين',
  'garbage bag': 'الحقائب والتخزين',
  'gym bag': 'الحقائب والتخزين',
  'laundry bag': 'الحقائب والتخزين',
  'lunch box': 'الحقائب والتخزين',
  'pencil case': 'الحقائب والتخزين',
  'plastic bag': 'الحقائب والتخزين',
  'shoe bag': 'الحقائب والتخزين',
  'wet bag': 'الحقائب والتخزين',
  'binder': 'الحقائب والتخزين',
  'folder': 'الحقائب والتخزين',

  // ── Food / drinks
  'coffee tumbler': 'الأكل والشرب',
  'electrolyte plus': 'الأكل والشرب',
  'energy drink': 'الأكل والشرب',
  'gum': 'الأكل والشرب',
  'protein bar': 'الأكل والشرب',
  'protein shake': 'الأكل والشرب',
  'protein shaker': 'الأكل والشرب',
  'snack': 'الأكل والشرب',
  'water bottle': 'الأكل والشرب',
  'pre workout': 'الأكل والشرب',

  // ── Travel / movement
  'boarding ticket': 'السفر والتنقل',
  'car keys': 'السفر والتنقل',
  'compass': 'السفر والتنقل',
  'keys': 'السفر والتنقل',
  'lock': 'السفر والتنقل',
  'locker lock': 'السفر والتنقل',
  'neck pillow': 'السفر والتنقل',
  'padlock': 'السفر والتنقل',
  'passport': 'السفر والتنقل',

  // ── Health / safety
  'bandages': 'الصحة والسلامة',
  'ear plugs': 'الصحة والسلامة',
  'first aid kit': 'الصحة والسلامة',
  'muscle ointment': 'الصحة والسلامة',
  'sleep mask': 'الصحة والسلامة',
  'stress ball': 'الصحة والسلامة',
};
